import type { Metadata } from "next";
import { Inter, Quicksand } from 'next/font/google'

import localFont from "next/font/local";
import "./globals.css";
import Nav from "./components/Nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})
const quickSand = Quicksand({
  subsets: ['latin'],
  display: 'swap',
})
 
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Umar Suhail- Frontend developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`antialiased dark font-quickSand ${quickSand.className}`}
        >
        <Nav></Nav>
        {children}
      </body>
    </html>
  );
}
