import type { Metadata } from "next";
import {  Quicksand } from 'next/font/google'
import "./globals.css";
import Nav from "./components/Nav";

const quickSand = Quicksand({
  subsets: ['latin'],
  display: 'swap',
})
 


export const metadata: Metadata = {
  title: "Umar Suhail- Frontend developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`antialiased dark font-quickSand ${quickSand.className}`}
        >
        <Nav></Nav>
        {children}
      </body>
    </html>
  );
}
